workflow:
  orthophoto:
    source_resolution:
    output_resolution: 0.5
  fusion:
    modify_flair: false
    keep_class_lidar1: true
    flair_only_herbaceous: false
  legacy:
    run_legacy_fusion: false
    apply_lidar_correction: true

lidar:
  vegetation_classes:
    - 3
    - 4
    - 5
    - 8
  optional_class_1: 1
  mask_excluded_value: 255
  height_thresholds:
    low_to_medium: 0.30
    medium_to_high: 5.0

flair:
  mask_excluded_value: 255
  height_thresholds:
    low_to_medium: 0.3
    medium_to_high: 5.0
  reweight:
    weights:
      0: 1
      1: 1
      2: 1
      3: 1
      4: 1
      5: 1
      6: 1
      7: 1
      8: 3
      9: 1
      10: 1
      11: 1
      12: 1
      13: 1
      14: 10
      15: 1
      16: 1
      17: 1
      18: 1
    mapping:
      8: 0
      14: 1
      12: 2
      13: 3
    ignore_value: 255

evaluation:
  reference_remap:
    1: 0
    2: 1
    3: 1
    4: 2
    5: 2
  prediction_remap:
    0: 0
    1: 1
    2: 2
    3: 2
  class_names:
    0: Grass
    1: Bush
    2: Tree
    3: Other
  empty_class_id: 3
